[project]
name = "portfolio-project"
version = "0.1.0"
description = ""
authors = [
    {name = "Mery Mailén Anelo",email = "anelomery@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django (>=5.1.5,<6.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "django-debug-toolbar (>=5.0.1,<6.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
