# Generated by Django 2.2.12 on 2021-03-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='subtitle',
            new_name='slug',
        ),
    ]
